markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
exclude: ["vendor"]

name: Ryan Mettler
url: http://www.graylords.com
description: Rubber, meet Road - A history of my trades.
twitter: ryanmettler
github: ryanmettler

